#####Compustat#####
comp_rd_val = F
if(comp_rd_val == T) cstat_df <- data.frame()
compustat_create <- function(rd = T){
  source("C:/Users/wfran/Dropbox/Research Projects/Financing Decisions/code/R/construct data/Functions/inflation.R")
  deflation()
  if(rd == T){
    cstat_df <<- read_dta("C:/Users/wfran/Dropbox/Data/Compustat/1970_2022_Compustat.dta")
  }
  print("done reading in...")
  comp_vars = c("gvkey","fyear","sic","cusip","CHE", "ACT", "LCT", "AT", "PPENT", "DLTT", "dd",
                "PSTKL", "SALE", "DP", "XINT", "TXT","NI","prcc_f","prcc_c", "dcs", "dcvsr", "dcvsub",
                "IB", "CSHO", "AJEX", "DLC", "TXDITC", "RE", "XRD", "TLCF", "PSTKRV", "DCVT", "ESUBC",
                "SPPE", "SIV", "FSRCT", "IVCH", "FUSET", "IBC", "XIDOC", "DPC", "TXDC", "DV", "CAPX",
                "AQC", "WCAPCH", "LT", "XSGA", "SPPIV", "FOPO", "FSRCO", "FUSEO", "WCAPC", "dcpstk",
                "CHECH", "DLCCH", "RECCH", "INVCH", "APALCH", "TXACH", "AOLOCH", "IVACO", "FIAO", "EXRE")

  comp_vars <- unlist(lapply(comp_vars,tolower))
  #cstat_df$pstkl[which(is.na(cstat_df$pstkl))] = cstat_df$pstkrv[which(is.na(cstat_df$pstkl))]
  cstat_df <<- as.data.table(cstat_df)
  cstat_df <<- cstat_df[,..comp_vars]
  function()
  cstat_df <<- cstat_df %>% arrange(gvkey, -fyear)
  cstat_df <<- cstat_df %>% mutate(sic = as.numeric(sic))
  cstat_df <<- cstat_df %>% mutate(sic3 = floor(sic/10))
  cstat_df <<- cstat_df %>% mutate(sic2 = floor(sic/100))
  cstat_df <<- cstat_df %>% mutate(sic1 = floor(sic/1000))
  cstat_df <<- cstat_df %>% group_by(gvkey) %>% mutate(minyear = min(fyear))
  cstat_df <<- cstat_df %>% group_by(gvkey) %>% mutate(fyear_t_1 = Lag(fyear, -1))
  cstat_df <<- cstat_df %>% group_by(gvkey) %>% mutate(fyear_tp_2 = Lag(fyear, +2))
  cstat_df <<- cstat_df %>% group_by(gvkey) %>% mutate(fyear_tp_1 = Lag(fyear, +1))
  cstat_df <<- merge(cstat_df, dff, by = c("fyear"))
  do.call(function(df){
    df <- df %>% mutate(che = che/CPIAUCSL)
    df <- df %>% mutate(act = act/CPIAUCSL)
    df <- df %>% mutate(lct = lct/CPIAUCSL)
    df <- df %>% mutate(at = at/CPIAUCSL)
    df <- df %>% mutate(ppent = ppent/CPIAUCSL)
    df <- df %>% mutate(dltt = dltt/CPIAUCSL)
    df <- df %>% mutate(dd = dd/CPIAUCSL)
    df <- df %>% mutate(pstkl = pstkl/CPIAUCSL)
    df <- df %>% mutate(sale = sale/CPIAUCSL)
    df <- df %>% mutate(dp = dp/CPIAUCSL)
    df <- df %>% mutate(xint = xint/CPIAUCSL)
    df <- df %>% mutate(txt = txt/CPIAUCSL)
    df <- df %>% mutate(ni = ni/CPIAUCSL)
    df <- df %>% mutate(dcs = dcs/CPIAUCSL)
    df <- df %>% mutate(dcvsr = dcvsr/CPIAUCSL)
    df <- df %>% mutate(dcvsub = dcvsub/CPIAUCSL)
    df <- df %>% mutate(ib = ib/CPIAUCSL)
    df <- df %>% mutate(ajex = ajex/CPIAUCSL)
    df <- df %>% mutate(dlc = dlc/CPIAUCSL)
    df <- df %>% mutate(txditc = txditc/CPIAUCSL)
    df <- df %>% mutate(re = re/CPIAUCSL)
    df <- df %>% mutate(xrd = xrd/CPIAUCSL)
    df <- df %>% mutate(tlcf = tlcf/CPIAUCSL)
    df <- df %>% mutate(pstkrv = pstkrv/CPIAUCSL)
    df <- df %>% mutate(dcvt = dcvt/CPIAUCSL)
    df <- df %>% mutate(esubc = esubc/CPIAUCSL)
    df <- df %>% mutate(sppe = sppe/CPIAUCSL)
    df <- df %>% mutate(siv = siv/CPIAUCSL)
    df <- df %>% mutate(fsrct = fsrct/CPIAUCSL)
    df <- df %>% mutate(ivch = ivch/CPIAUCSL)
    df <- df %>% mutate(fuset = fuset/CPIAUCSL)
    df <- df %>% mutate(ibc = ibc/CPIAUCSL)
    df <- df %>% mutate(xidoc = xidoc/CPIAUCSL)
    df <- df %>% mutate(dpc = dpc/CPIAUCSL)
    df <- df %>% mutate(txdc = txdc/CPIAUCSL)
    df <- df %>% mutate(dv = dv/CPIAUCSL)
    df <- df %>% mutate(capx = capx/CPIAUCSL)
    df <- df %>% mutate(aqc = aqc/CPIAUCSL)
    df <- df %>% mutate(wcapch = wcapch/CPIAUCSL)
    df <- df %>% mutate(lt = lt/CPIAUCSL)
    df <- df %>% mutate(xsga = xsga/CPIAUCSL)
    df <- df %>% mutate(sppiv = sppiv/CPIAUCSL)
    df <- df %>% mutate(fopo = fopo/CPIAUCSL)
    df <- df %>% mutate(fsrco = fsrco/CPIAUCSL)
    df <- df %>% mutate(fuseo = fuseo/CPIAUCSL)
    df <- df %>% mutate(wcapc = wcapc/CPIAUCSL)
    df <- df %>% mutate(dcpstk = dcpstk/CPIAUCSL)
    df <- df %>% mutate(chech = chech/CPIAUCSL)
    df <- df %>% mutate(dlcch = dlcch/CPIAUCSL)
    df <- df %>% mutate(recch = recch/CPIAUCSL)
    df <- df %>% mutate(invch = invch/CPIAUCSL)
    df <- df %>% mutate(apalch = apalch/CPIAUCSL)
    df <- df %>% mutate(txach = txach/CPIAUCSL)
    df <- df %>% mutate(aoloch = aoloch/CPIAUCSL)
    df <- df %>% mutate(ivaco = ivaco/CPIAUCSL)
    df <- df %>% mutate(fiao = fiao/CPIAUCSL)
    df <- df %>% mutate(exre = exre/CPIAUCSL)
    df <- df %>% group_by(gvkey) %>% mutate(che_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(che, -1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(ni_t_1 = ifelse(fyear == fyear_t_1+1,Lag(ni, -1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dlc_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dlc, -1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(at_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(at, -1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dv_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(dv,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(prcc_c_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(prcc_c,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(ajex_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(ajex, -1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(csho_t_1 =  ifelse(fyear == fyear_t_1 + 1,Lag(csho, -1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dcpstk_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcpstk,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dcs_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcs,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dcvsr_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcvsr,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dcvsub_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcvsub,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dcvt_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcvt,-1),NA))
    df <- df %>% group_by(gvkey) %>% mutate(dd_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dd,-1),NA))
    df_list <<- list(df_list, df)
  }, list(cstat_df))
  
  do.call(function(df){
      df <- df %>% group_by(gvkey) %>% mutate(che_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(che, -1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(ni_t_1 = ifelse(fyear == fyear_t_1+1,Lag(ni, -1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dlc_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dlc, -1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(at_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(at, -1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dv_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(dv,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(prcc_c_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(prcc_c,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(ajex_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(ajex, -1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(csho_t_1 =  ifelse(fyear == fyear_t_1 + 1,Lag(csho, -1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dcpstk_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcpstk,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dcs_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcs,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dcvsr_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcvsr,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dcvsub_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcvsub,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dcvt_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dcvt,-1),NA))
      df <- df %>% group_by(gvkey) %>% mutate(dd_t_1 = ifelse(fyear == fyear_t_1+1,Lag(dd,-1),NA))
      df_list <<- list(df_list, df)
    }, list(cstat_df))
}
compustat_create(rd = comp_rd_val)
compustat_levels <- function(df){
  ####Levels Variables####
  df <- df %>% rowwise() %>% mutate(BookEquity = sum(at,-lt,-pstkrv, txditc, dcvt, na.rm = T))
  df <- df %>% rowwise() %>% mutate(Debt = sum(dltt,dlc,na.rm = T))
  df <- df %>% group_by(gvkey) %>% mutate(Debt_t_1 = ifelse(fyear == fyear_t_1 + 1,Lag(Debt, -1),NA))
  df <- df %>% mutate(MV = csho*prcc_c)
  df <- df %>% rowwise() %>% mutate(mvat = sum(dlc,MV,na.rm = T))
  return(df)
}
compusat_flow <- function(df){
  #####Flow Variables#####
  df <- df %>% rowwise() %>% mutate(Cash_Flow_post_1986 = sum(ibc, xidoc, dpc, txdc, esubc, fopo, sppiv, fsrco, na.rm = T))
  df <- df %>% rowwise() %>% mutate(Cash_Flow_pre_1987 = sum(ibc, xidoc, dpc, txdc, esubc, fopo, fsrco, na.rm = T))
  df <- df %>% rowwise() %>% mutate(Cash_Flow_7 = sum(ibc, xidoc, dpc, txdc, esubc, fopo, sppiv, exre, na.rm = T))
  df <- df %>% rowwise() %>% mutate(Investment_1_2_3 = sum(capx, ivch, aqc, fuseo, -sppe, -siv,na.rm = T))
  df <- df %>% rowwise() %>% mutate(Investment_7 = sum(ivch, -siv, capx, -sppe, aqc, -ivaco, na.rm = T))
  return(df)
}
change_of_levels <- function(df){
  #####Change of Variables#####
  df <- df %>% mutate(delta_che = che - che_t_1 )
  df <- df %>% mutate(delta_debt = Debt - Debt_t_1)
  df <- df %>% mutate(delta_csho = csho - csho_t_1)
  df <- df %>% rowwise() %>% mutate(change_nwc_1 = sum(-wcapch, che, -che_t_1,dlc, - dlc_t_1,na.rm = T)) 
  df <- df %>% rowwise() %>% mutate(change_nwc_2 = sum(-fsrct, fuset, che,-che_t_1, -dlcch,na.rm = T))
  df <- df %>% rowwise() %>% mutate(change_nwc_3 = sum(wcapc, -chech, che, -che_t_1,na.rm = T))
  df <- df %>% rowwise() %>% mutate(change_nwc_7 = sum(recch, invch, apalch, txach, aoloch, fiao,na.rm = T))
  df <- df %>% mutate(StockReturn= (prcc_c/(prcc_c_t_1*(ajex/ajex_t_1)))-1)
  return(df)
}
ratio_of_levels <- function(df){
  #####Ratio Levels#####
  df <- df %>% mutate(Current_Ratio = act/lct)
  df <- df %>% mutate(Market_Leverage = Debt/mvat)
  df <- df %>% mutate(Book_Leverage = Debt/at)
  df <- df %>% mutate(cash_to_assets = che/at_t_1)
  df <- df %>% mutate(Debt_to_assets = Debt/at_t_1)
  return(df)
}
ratio_of_flow <- function(df){
  #####Ratio Flow#####
  df <- df %>% mutate(RD_Sales  = xrd/sale)
  df <- df %>% mutate(Ammortization = dp/at)
  df <- df %>% mutate(Selling_Expense = xsga/sale)
  return(df)
}